import {MigrationInterface, QueryRunner} from "typeorm";

export class tagColor1622451879582 implements MigrationInterface {
    name = 'tagColor1622451879582'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "file_tags" ADD "color" character varying(300) NOT NULL DEFAULT '#333333'`);
        await queryRunner.query(`COMMENT ON COLUMN "permissions"."createdAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "permissions"."updatedAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "roles"."createdAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "roles"."updatedAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "domains"."createdAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "domains"."updatedAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "profiles"."createdAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "profiles"."updatedAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "requests"."createdAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "requests"."updatedAt" IS NULL`);
        await queryRunner.query(`ALTER TYPE "public"."statusEnum" RENAME TO "statusEnum_old"`);
        await queryRunner.query(`CREATE TYPE "statusEnum" AS ENUM('created', 'updated', 'accepted', 'refused')`);
        await queryRunner.query(`ALTER TABLE "requests" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "requests" ALTER COLUMN "status" TYPE "statusEnum" USING "status"::"text"::"statusEnum"`);
        await queryRunner.query(`ALTER TABLE "requests" ALTER COLUMN "status" SET DEFAULT 'created'`);
        await queryRunner.query(`DROP TYPE "statusEnum_old"`);
        await queryRunner.query(`COMMENT ON COLUMN "requests"."status" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "subscriptions"."createdAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "subscriptions"."updatedAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "sessions"."createdAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "sessions"."updatedAt" IS NULL`);
        await queryRunner.query(`ALTER TYPE "public"."sessionEnum" RENAME TO "sessionEnum_old"`);
        await queryRunner.query(`CREATE TYPE "sessionEnum" AS ENUM('created', 'updated', 'accepted', 'refused', 'activated', 'done')`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "status" TYPE "sessionEnum" USING "status"::"text"::"sessionEnum"`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "status" SET DEFAULT 'created'`);
        await queryRunner.query(`DROP TYPE "sessionEnum_old"`);
        await queryRunner.query(`COMMENT ON COLUMN "sessions"."status" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "messages"."createdAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "messages"."updatedAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "rooms"."createdAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "rooms"."updatedAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "events"."createdAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "events"."updatedAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "badges"."createdAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "badges"."updatedAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "points"."createdAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "points"."updatedAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "balances"."createdAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "balances"."updatedAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "quizSolutions"."createdAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "quizSolutions"."updatedAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "quizzes"."createdAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "quizzes"."updatedAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "objectifs"."createdAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "objectifs"."updatedAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."createdAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."updatedAt" IS NULL`);
        await queryRunner.query(`ALTER TYPE "public"."userStatusEnum" RENAME TO "userStatusEnum_old"`);
        await queryRunner.query(`CREATE TYPE "userStatusEnum" AS ENUM('open', 'close', 'away', 'busy')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" TYPE "userStatusEnum" USING "status"::"text"::"userStatusEnum"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" SET DEFAULT 'open'`);
        await queryRunner.query(`DROP TYPE "userStatusEnum_old"`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."status" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "files"."createdAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "files"."updatedAt" IS NULL`);
        await queryRunner.query(`ALTER TYPE "public"."fileStatusEnum" RENAME TO "fileStatusEnum_old"`);
        await queryRunner.query(`CREATE TYPE "fileStatusEnum" AS ENUM('created', 'updated', 'deleted', 'shared')`);
        await queryRunner.query(`ALTER TABLE "files" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "files" ALTER COLUMN "status" TYPE "fileStatusEnum" USING "status"::"text"::"fileStatusEnum"`);
        await queryRunner.query(`ALTER TABLE "files" ALTER COLUMN "status" SET DEFAULT 'created'`);
        await queryRunner.query(`DROP TYPE "fileStatusEnum_old"`);
        await queryRunner.query(`COMMENT ON COLUMN "files"."status" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "file_tags"."createdAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "file_tags"."updatedAt" IS NULL`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`COMMENT ON COLUMN "file_tags"."updatedAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "file_tags"."createdAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "files"."status" IS NULL`);
        await queryRunner.query(`CREATE TYPE "fileStatusEnum_old" AS ENUM()`);
        await queryRunner.query(`ALTER TABLE "files" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "files" ALTER COLUMN "status" TYPE "fileStatusEnum_old" USING "status"::"text"::"fileStatusEnum_old"`);
        await queryRunner.query(`ALTER TABLE "files" ALTER COLUMN "status" SET DEFAULT 'created'`);
        await queryRunner.query(`DROP TYPE "files_status_enum"`);
        await queryRunner.query(`ALTER TYPE "fileStatusEnum_old" RENAME TO  "fileStatusEnum"`);
        await queryRunner.query(`COMMENT ON COLUMN "files"."updatedAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "files"."createdAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."status" IS NULL`);
        await queryRunner.query(`CREATE TYPE "userStatusEnum_old" AS ENUM()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" TYPE "userStatusEnum_old" USING "status"::"text"::"userStatusEnum_old"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "status" SET DEFAULT 'open'`);
        await queryRunner.query(`DROP TYPE "users_status_enum"`);
        await queryRunner.query(`ALTER TYPE "userStatusEnum_old" RENAME TO  "userStatusEnum"`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."updatedAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."createdAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "objectifs"."updatedAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "objectifs"."createdAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "quizzes"."updatedAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "quizzes"."createdAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "quizSolutions"."updatedAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "quizSolutions"."createdAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "balances"."updatedAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "balances"."createdAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "points"."updatedAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "points"."createdAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "badges"."updatedAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "badges"."createdAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "events"."updatedAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "events"."createdAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "rooms"."updatedAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "rooms"."createdAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "messages"."updatedAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "messages"."createdAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "sessions"."status" IS NULL`);
        await queryRunner.query(`CREATE TYPE "sessionEnum_old" AS ENUM()`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "status" TYPE "sessionEnum_old" USING "status"::"text"::"sessionEnum_old"`);
        await queryRunner.query(`ALTER TABLE "sessions" ALTER COLUMN "status" SET DEFAULT 'created'`);
        await queryRunner.query(`DROP TYPE "sessions_status_enum"`);
        await queryRunner.query(`ALTER TYPE "sessionEnum_old" RENAME TO  "sessionEnum"`);
        await queryRunner.query(`COMMENT ON COLUMN "sessions"."updatedAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "sessions"."createdAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "subscriptions"."updatedAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "subscriptions"."createdAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "requests"."status" IS NULL`);
        await queryRunner.query(`CREATE TYPE "statusEnum_old" AS ENUM()`);
        await queryRunner.query(`ALTER TABLE "requests" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "requests" ALTER COLUMN "status" TYPE "statusEnum_old" USING "status"::"text"::"statusEnum_old"`);
        await queryRunner.query(`ALTER TABLE "requests" ALTER COLUMN "status" SET DEFAULT 'created'`);
        await queryRunner.query(`DROP TYPE "requests_status_enum"`);
        await queryRunner.query(`ALTER TYPE "statusEnum_old" RENAME TO  "statusEnum"`);
        await queryRunner.query(`COMMENT ON COLUMN "requests"."updatedAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "requests"."createdAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "profiles"."updatedAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "profiles"."createdAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "domains"."updatedAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "domains"."createdAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "roles"."updatedAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "roles"."createdAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "permissions"."updatedAt" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "permissions"."createdAt" IS NULL`);
        await queryRunner.query(`ALTER TABLE "file_tags" DROP COLUMN "color"`);
    }

}
